### PR TITLE
Fix false positive in  cop.

### LINKED ISSUE #595: False positive in RSpec/Pending
We have a scope defined on an ActiveRecord model called 'pending'.

The RSpec/Pending cop is falsely flagging this as an issue on a line as below:

`subject { Vacancy.pending }`

### PR DESCRIPTION
**Pull request by Darhazer**
The `send_pattern` in language does not specify receiver. Usually the receiver must be either `nil?` or `RSpec`. When not-specified, a method named like some of the language methods would trigger false positive.

Fixes #595 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] ~Updated documentation (run `rake generate_cops_documentation`).~
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) is passing.

If you have created a new cop:
* [ ] Added the new cop to `config/default.yml`.
* [ ] The cop includes examples of good and bad code.
* [ ] You have tests for both code that should be reported and code that is good.

### CODE REVIEW

File: lib/rubocop/cop/rspec/pending.rb [hunk 1]
```diff
@@ -65,6 +67,10 @@ def skip_node?(node)
         def skip_symbol?(symbol_node)
           symbol_node == SKIP_SYMBOL || symbol_node == PENDING_SYMBOL
         end
+
+        def rspec?(node)
+          node.nil? || (node.const_type? && node.const_name == 'RSpec')
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/pending.rb]: Would it be possible to instead use our usual `{(const nil? :RSpec) nil?}` node matcher?

Comment (Darhazer) [reply lib/rubocop/cop/rspec/pending.rb]: Possible, if match is performed on the send node, and not on the receiver (as `receiver` may return nil instead of ast::node). Updated.
